trigger:
- master
- features/*

variables:
  buildConfiguration: 'release'
  project.path: 'src\$(Project.Name)'
  version.major: 0
  version.minor: 0
  version.patch: 0

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - script: |
        dotnet build $(Project.Path) -c $(buildConfiguration)
        dotnet pack $(Project.Path) -c $(buildConfiguration) /p:PackageVersion=$(version.major).$(version.minor).$(version.patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore

    - task: PublishBuildArtifacts@1