trigger:
- master
- features/*

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: PowerShell@2
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.ps1  

#  - task: NuGetCommand@2
#    displayName: 'MyGet push'
#    inputs:
#      command: push
#      packagesToPush: 'nuget/*.nupkg'
#      nuGetFeedType: external
#      publishFeedCredentials: 'MyGet'
#      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))